sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1833404799
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wxf83109f54a043dfe
    secert: e96f8879545b1ee5d80784818e39eb7e
